# ch03_srs.py
import sys
sys.path.insert(0, r'C:\ai-agent')
from ql_helpers import *
from ql_helpers import _p, _r, _sup

def write_ch3(doc):
    chapter_heading(doc, "3", "Software Requirements Specification")

    section(doc, "3.1", "Assumptions and Dependencies")
    body(doc,
        "The following assumptions apply to the QuickLearner AI system. The end user "
        "has access to a modern web browser (Chrome, Firefox, or Edge) and a stable "
        "internet connection. The Google Gemini API is available and the configured "
        "API key has sufficient quota for all AI operations. The system is deployed "
        "on a machine running Python 3.10 or later and Node.js 18 or later. "
        "The SQLite database is used for single-user or small-group deployments; "
        "migration to PostgreSQL is assumed for production-scale use.")
    body(doc,
        "The system depends on the following external services and libraries: "
        "Google Gemini API for all AI content generation, FastAPI and Uvicorn for "
        "the backend server, SQLAlchemy for database ORM, React.js and Tailwind CSS "
        "for the frontend, and Framer Motion for UI animations.")

    section(doc, "3.2", "Functional Requirements")
    subsection(doc, "3.2.1", "Feature 1: AI Chat Assistant")
    body(doc,
        "The system shall provide a conversational AI chat interface that accepts "
        "natural language queries from the student and returns contextually accurate "
        "responses generated by the Gemini API. The chat interface shall maintain "
        "session context across multiple conversation turns. The student shall be able "
        "to start a new chat session at any time. All chat sessions shall be persisted "
        "in the database for future reference.")

    subsection(doc, "3.2.2", "Feature 2: AI Quiz Generator")
    body(doc,
        "The system shall generate multiple-choice quiz questions from any text input "
        "provided by the student using the Gemini API. Each quiz shall contain a "
        "configurable number of questions (default: 5). Each question shall include "
        "four answer options and identify the correct answer. Quiz results shall be "
        "stored in the database and reflected in the Analytics dashboard.")

    subsection(doc, "3.2.3", "Feature 3: Flashcards, Summariser, Notes Highlighter")
    body(doc,
        "The Flashcard module shall generate question-answer pairs from student-provided "
        "text. The Text Summariser shall produce a concise abstractive summary of input "
        "content. The Notes Highlighter shall identify and return the most important "
        "sentences and key concepts from the input text. All generated content shall "
        "be persistently stored and retrievable by the student.")

    subsection(doc, "3.2.4", "Feature 4: Analytics, Goals, Streak, Dashboard")
    body(doc,
        "The Analytics module shall display charts and metrics for study time, quiz "
        "scores, feature usage frequency, and daily activity. The Daily Goals feature "
        "shall allow students to set and track daily study objectives. The Daily Streak "
        "shall automatically count consecutive days of platform activity and display "
        "the current streak count. The Dashboard shall provide a unified overview of "
        "all features, recent activity, and progress metrics.")

    section(doc, "3.3", "External Interface Requirements")
    subsection(doc, "3.3.1", "User Interfaces")
    body(doc,
        "The system shall provide a web-based single-page application accessible via "
        "any modern browser. The UI shall be responsive and function correctly on both "
        "desktop and tablet screen sizes. All interactive elements shall be accessible "
        "and provide visual feedback on hover and click. The interface shall support "
        "dark mode by default.")

    subsection(doc, "3.3.2", "Hardware Interfaces")
    body(doc,
        "The system requires no specialised hardware. A standard computer or tablet "
        "with a keyboard, mouse or touch input, and display is sufficient. The system "
        "shall function correctly at screen resolutions of 1280×720 and above.")

    subsection(doc, "3.3.3", "Software Interfaces")
    body(doc,
        "Frontend communicates with the backend via RESTful HTTP APIs using JSON "
        "payloads. The backend communicates with the Google Gemini API using the "
        "official Python SDK. The backend reads from and writes to the SQLite database "
        "via SQLAlchemy ORM. CORS is configured to allow cross-origin requests from "
        "the frontend origin.")

    subsection(doc, "3.3.4", "Communication Interfaces")
    body(doc,
        "All communication between the frontend and backend uses the HTTP/HTTPS "
        "protocol. API requests are made using the Fetch API in the frontend. "
        "All data is serialised and deserialised as JSON. The Gemini API is accessed "
        "over HTTPS using the Google AI Python SDK.")

    section(doc, "3.4", "Non-Functional Requirements")
    subsection(doc, "3.4.1", "Performance Requirements")
    body(doc,
        "The system shall deliver AI-generated responses within 5 seconds for standard "
        "queries under normal network conditions. The frontend shall load within 3 "
        "seconds on a standard broadband connection. The backend API shall handle "
        "concurrent requests without significant degradation in response time.")

    subsection(doc, "3.4.2", "Security Requirements")
    body(doc,
        "The Google Gemini API key shall be stored as an environment variable and "
        "never exposed to the frontend. All database operations shall use parameterised "
        "queries via SQLAlchemy ORM to prevent SQL injection. CORS policy shall "
        "restrict API access to the configured frontend origin.")

    subsection(doc, "3.4.3", "Usability Requirements")
    body(doc,
        "The interface shall be intuitive enough for a first-time user to navigate "
        "all features without training. All error states shall display clear, "
        "human-readable messages. The system shall provide loading indicators for "
        "all asynchronous AI operations.")

    subsection(doc, "3.4.4", "Maintainability Requirements")
    body(doc,
        "The codebase shall be modular with clear separation of concerns between the "
        "AI layer, API layer, database layer, and UI layer. Each feature shall be "
        "encapsulated in its own backend router and frontend component. Code shall "
        "be documented with inline comments and type annotations.")

